name: incoming-handler
on:
  push:
    paths:
      - 'incoming/**'

jobs:
  handle-oldest-incoming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Find oldest incoming file
        id: find
        run: |
          # List incoming/*.txt in repo
          files=$(find incoming -maxdepth 1 -type f -name '*.txt' | sort)
          if [ -z "$files" ]; then
            echo "files=" >> "$GITHUB_OUTPUT"
            echo "No incoming files found."
            exit 0
          fi

          # Pick the oldest file
          oldest=$(echo "$files" | head -n1)
          echo "Processing oldest file: $oldest"
          echo "files=$oldest" >> "$GITHUB_OUTPUT"

      - name: Create output for oldest file
        if: steps.find.outputs.files != ''
        run: |
          f="${{ steps.find.outputs.files }}"
          echo "Processing $f"
          uuid=$(basename "$f" .txt)
          url=$(tr -d '\r' < "$f")
          mkdir -p output
          out="output/${uuid}-output.txt"
          printf "%s\n" \
            "----------------------------------" \
            "IPA Processing Complete" \
            "----------------------------------" \
            "" \
            "Original URL: ${url}" \
            "UUID: ${uuid}" \
            "Processed: $(date)" \
            "" \
            "----------------------------------" \
            > "${out}"
          echo "Created ${out}"

      - name: Upload output as artifact
        if: steps.find.outputs.files != ''
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: output/

      - name: Delete processed file
        if: steps.find.outputs.files != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          f="${{ steps.find.outputs.files }}"
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git rm -f "$f"
          git commit -m "Remove processed file ${f}" || echo "nothing to commit"
          git push origin HEAD || echo "push failed"
